### PR TITLE
hack to make auth delegation work

### PR DESCRIPTION
**Pull request by dylanwh**
I had to change these things to get it running. I had it running successfully as https://bzdeck.hardison.net 👍

### CODE REVIEW

**Comment by kyoshino** [comment]
That's awesome, but the PHP dev server (bin/dev-router.php) is not used on production. I'm not using it locally neither. :confused:

**Comment by kyoshino** [comment]
I just checked the Apache log again to find this:

> 66.207.***.** - - [08/Apr/2016:15:44:07 -0400] "GET /integration/bugzilla-auth-callback/&description=BzDeck HTTP/2" 404 0 "https://www.bzdeck.com/service-worker.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0"

Is this you?

**Comment by dylanwh** [comment]
yep, that was me. I doubted these changes would make it work in production, but it proves that production bugzilla can connect to bzdeck. Just not production bzdeck. :-/

**Comment by kyoshino** [comment]
Okay, I'm about to merge this. Still not sure why Apache doesn't get any auth callback requests.

**Comment by kyoshino** [comment]
I'll create a support ticket with [my hosting company](https://www.digitalocean.com/) to ask if they are blocking the IP or user agent.

**Comment by kyoshino** [comment]
A tech support guy says they are not blocking anything at the BzDeck server side. :confused:

**Pull request merged**
